# These are supported funding model platforms

github: # bensalcie
patreon: # bensalcie
open_collective: # bensalcie
ko_fi: # bensalcie
tidelift: # [npn/bensalcie]
community_bridge: # ben-salcie
liberapay: # bensalcie
issuehunt: # bensalcie
otechie: # bensalcie
custom: # ['http://bensalcie.likesyou.org/?i=1', 'http://bensalcie.likesyou.org/?i=1']
